source 'https://rubygems.org'

gem 'middleman',             '~> 3.3.7'
gem 'middleman-alias'
gem 'middleman-blog',        '~> 3.6.0.beta.2'
gem 'middleman-livereload'
gem 'middleman-deploy'
gem 'bootstrap-sass'
gem 'compass'
gem 'nokogiri'
gem 'rack-rewrite'
gem 'russian'
